import './style.css';

const SERVER_URL = import.meta.env.VITE_SERVER_URL || (location.protocol === 'https:' ? `wss://${location.host}` : `ws://${location.hostname}:3001`);
const WORLD = { width: 2400, height: 1500 };
const CHAT_RADIUS = 360;
const VOICE_RADIUS = 260;
const ICE_SERVERS = [{ urls:'stun:stun.l.google.com:19302' }, { urls:'stun:stun1.l.google.com:19302' }];

const state = { socket:null, connected:false, players:new Map(), messages:[], pendingChats:[], keys:new Set(), micStream:null, peers:new Map(), audio:new Map(), id:crypto.randomUUID(), name:`Player${Math.floor(100+Math.random()*900)}`, x:WORLD.width/2, y:WORLD.height/2, speed:5 };
const app=document.querySelector('#root');
app.innerHTML=`<div class="app"><header class="topbar"><div class="brand"><span class="brand-dot"></span><strong>Proxy</strong><span>Chat</span></div><div class="status"><i id="statusDot"></i><span id="statusText">Connexion…</span></div><button class="ghost" id="profileBtn">👤 <span id="profileName"></span></button></header><main class="game-shell"><section class="world-wrap"><canvas id="world" width="1200" height="760"></canvas><div class="hint">🕹️ Joystick ou <b>ZQSD</b> pour bouger · <b>Entrée</b> pour envoyer</div><div class="voice-pill" id="voicePill">🎙️ Micro désactivé</div><div class="coords" id="coords">X: 1200 · Y: 750</div></section><aside class="chat-panel"><div class="chat-head"><div><h1>Chat de proximité</h1><p id="nearby">Recherche des joueurs…</p></div><span class="live">LIVE</span></div><div class="messages" id="messages"></div><form class="composer" id="composer"><input id="messageInput" maxlength="180" autocomplete="off" placeholder="Écris aux personnes proches…" /><button type="submit" aria-label="Envoyer">➤</button></form><div class="controls"><button class="control" id="micBtn">🎙️ Activer le micro</button><button class="control" id="centerBtn">⌖ Recentrer</button></div><div class="teleport"><div class="section-title">📍 Téléportation</div><div class="my-coords">Tes coordonnées : <b id="myCoords">X: 1200 · Y: 750</b></div><div class="tp-inputs"><input id="tpX" type="number" min="0" max="2400" placeholder="X"/><input id="tpY" type="number" min="0" max="1500" placeholder="Y"/><button id="tpBtn">Aller</button></div><div class="section-title players-title">👥 Joueurs</div><div id="playerList" class="player-list"><span class="empty">Aucun autre joueur</span></div></div></aside></main><div class="modal hidden" id="profileModal"><div class="modal-card"><button class="close" id="closeModal">×</button><h2>Ton profil</h2><label>Pseudo<input id="nameInput" maxlength="18" /></label><button class="primary" id="saveName">Enregistrer</button></div></div></div>`;

const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d'),messagesEl=document.querySelector('#messages'),nearbyEl=document.querySelector('#nearby'),statusDot=document.querySelector('#statusDot'),statusText=document.querySelector('#statusText'),input=document.querySelector('#messageInput'),micBtn=document.querySelector('#micBtn'),voicePill=document.querySelector('#voicePill'),coordsEl=document.querySelector('#coords'),myCoordsEl=document.querySelector('#myCoords'),playerListEl=document.querySelector('#playerList');
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function setStatus(ok,text){state.connected=ok;statusDot.className=ok?'ok':'';statusText.textContent=text;}
function addMessage(m){state.messages.push(m);state.messages=state.messages.slice(-60);messagesEl.innerHTML=state.messages.map(x=>`<div class="msg ${x.player?.id===state.id?'mine':''}"><div><b>${escapeHtml(x.name)}</b><span>${new Date(x.at||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div><p>${escapeHtml(x.text)}</p></div>`).join('');messagesEl.scrollTop=messagesEl.scrollHeight;}
function sendChat(){const text=input.value.trim();if(!text)return;const message={type:'chat',text};addMessage({name:state.name,text,at:Date.now(),player:{id:state.id,x:state.x,y:state.y}});if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify(message));else state.pendingChats.push(message);input.value='';input.focus();}
document.querySelector('#composer').addEventListener('submit',e=>{e.preventDefault();sendChat();});
function flushPendingChats(){if(state.socket?.readyState!==WebSocket.OPEN)return;for(const m of state.pendingChats)state.socket.send(JSON.stringify(m));state.pendingChats=[];}
function broadcastPosition(){if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({type:'move',x:state.x,y:state.y}));}
function updateCoords(){const text=`X: ${Math.round(state.x)} · Y: ${Math.round(state.y)}`;coordsEl.textContent=text;myCoordsEl.textContent=text;}
function renderPlayerList(){const list=[...state.players.values()];if(!list.length){playerListEl.innerHTML='<span class="empty">Aucun autre joueur</span>';return;}playerListEl.innerHTML=list.map(p=>`<div class="player-row"><div><b>${escapeHtml(p.name)}</b><small>X: ${Math.round(p.x)} · Y: ${Math.round(p.y)}</small></div><button data-teleport="${p.id}">📍 Aller</button></div>`).join('');playerListEl.querySelectorAll('[data-teleport]').forEach(btn=>btn.addEventListener('click',()=>{const p=state.players.get(btn.dataset.teleport);if(p)teleportTo(p.x,p.y);}));}
function teleportTo(x,y){state.x=Math.max(0,Math.min(WORLD.width,Number(x)||0));state.y=Math.max(0,Math.min(WORLD.height,Number(y)||0));broadcastPosition();updateCoords();}
function connect(){try{state.socket=new WebSocket(SERVER_URL);}catch{setStatus(false,'Hors ligne');return;}state.socket.onopen=()=>{setStatus(true,'En ligne');state.socket.send(JSON.stringify({type:'join',id:state.id,name:state.name,x:state.x,y:state.y}));flushPendingChats();};state.socket.onclose=()=>{setStatus(false,'Serveur indisponible');for(const id of state.peers.keys())closePeer(id);setTimeout(connect,2500);};state.socket.onerror=()=>setStatus(false,'Connexion interrompue');state.socket.onmessage=async e=>{const d=JSON.parse(e.data);if(d.type==='snapshot'){state.players.clear();for(const p of d.players)if(p.id!==state.id)state.players.set(p.id,p);updateNearby();renderPlayerList();}if(d.type==='player:join'&&d.player.id!==state.id){state.players.set(d.player.id,d.player);renderPlayerList();}if(d.type==='player:move'&&d.player.id!==state.id){state.players.set(d.player.id,d.player);renderPlayerList();}if(d.type==='player:name'&&d.player.id!==state.id){const p=state.players.get(d.player.id);if(p){p.name=d.player.name;renderPlayerList();}}if(d.type==='player:leave'){state.players.delete(d.id);closePeer(d.id);renderPlayerList();}if(d.type==='chat'){const mine=d.player?.id===state.id;if(!mine&&d.player&&distance(state,d.player)<=CHAT_RADIUS)addMessage(d);}if(d.type.startsWith('voice:'))await handleSignal(d);};}
function updateNearby(){const count=[...state.players.values()].filter(p=>distance(state,p)<=CHAT_RADIUS).length;nearbyEl.textContent=count?`${count} personne${count>1?'s':''} dans ta zone`:'Personne à proximité';}
window.addEventListener('keydown',e=>{if(e.key==='Enter'&&document.activeElement===input){e.preventDefault();sendChat();return;}if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;state.keys.add(e.key.toLowerCase());});window.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));
function update(){let dx=0,dy=0;if(state.keys.has('z')||state.keys.has('arrowup'))dy--;if(state.keys.has('s')||state.keys.has('arrowdown'))dy++;if(state.keys.has('q')||state.keys.has('arrowleft'))dx--;if(state.keys.has('d')||state.keys.has('arrowright'))dx++;if(dx||dy){const len=Math.hypot(dx,dy);state.x=Math.max(40,Math.min(WORLD.width-40,state.x+dx/len*state.speed));state.y=Math.max(40,Math.min(WORLD.height-40,state.y+dy/len*state.speed));broadcastPosition();}updateNearby();updateVoiceDistances();updateCoords();}
function worldToScreen(x,y){const scale=Math.min(canvas.width/WORLD.width,canvas.height/WORLD.height)*.98;return{x:canvas.width/2+(x-state.x)*scale,y:canvas.height/2+(y-state.y)*scale,scale};}
function drawPlayer(p,me=false){const s=worldToScreen(p.x,p.y);if(s.x<-50||s.x>canvas.width+50||s.y<-50||s.y>canvas.height+50)return;ctx.beginPath();ctx.arc(s.x,s.y,16,0,Math.PI*2);ctx.fillStyle=me?'#8b5cf6':'#22d3ee';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='rgba(255,255,255,.75)';ctx.stroke();ctx.font='600 14px Inter,system-ui';ctx.textAlign='center';ctx.fillStyle='#fff';ctx.fillText(p.name,s.x,s.y-25);}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);const grad=ctx.createLinearGradient(0,0,canvas.width,canvas.height);grad.addColorStop(0,'#111827');grad.addColorStop(1,'#0b1220');ctx.fillStyle=grad;ctx.fillRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/WORLD.width,canvas.height/WORLD.height)*.98;for(let x=-120;x<canvas.width+120;x+=80*scale)for(let y=-120;y<canvas.height+120;y+=80*scale){ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect(x,y,2,2);}const zoneR=CHAT_RADIUS*scale;ctx.beginPath();ctx.arc(canvas.width/2,canvas.height/2,zoneR,0,Math.PI*2);ctx.fillStyle='rgba(139,92,246,.06)';ctx.fill();ctx.strokeStyle='rgba(139,92,246,.2)';ctx.stroke();for(const p of state.players.values())drawPlayer(p);drawPlayer({x:state.x,y:state.y,name:state.name},true);requestAnimationFrame(render);}
function createPeer(id){if(state.peers.has(id))return state.peers.get(id);const pc=new RTCPeerConnection({iceServers:ICE_SERVERS});state.peers.set(id,pc);if(state.micStream)state.micStream.getTracks().forEach(t=>pc.addTrack(t,state.micStream));pc.onicecandidate=e=>e.candidate&&state.socket?.send(JSON.stringify({type:'voice:ice',to:id,candidate:e.candidate}));pc.ontrack=e=>{let a=state.audio.get(id);if(!a){a=document.createElement('audio');a.autoplay=true;a.playsInline=true;document.body.appendChild(a);state.audio.set(id,a);}a.srcObject=e.streams[0];a.play().catch(()=>{});};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))closePeer(id);};return pc;}
function closePeer(id){const pc=state.peers.get(id);if(pc)pc.close();state.peers.delete(id);const a=state.audio.get(id);if(a){a.srcObject=null;a.remove();}state.audio.delete(id);}
async function handleSignal(d){if(d.from===state.id)return;const pc=createPeer(d.from);try{if(d.type==='voice:offer'){await pc.setRemoteDescription(d.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);state.socket.send(JSON.stringify({type:'voice:answer',to:d.from,answer}));}else if(d.type==='voice:answer')await pc.setRemoteDescription(d.answer);else if(d.type==='voice:ice'&&d.candidate)await pc.addIceCandidate(d.candidate);}catch(err){console.warn('Voice signaling error',err);}}
async function startVoicePeer(id){const p=state.players.get(id);if(!state.micStream||!p||state.peers.has(id)||distance(state,p)>VOICE_RADIUS)return;const pc=createPeer(id);try{const offer=await pc.createOffer();await pc.setLocalDescription(offer);state.socket.send(JSON.stringify({type:'voice:offer',to:id,offer}));}catch(err){console.warn('Voice offer error',err);}}
function updateVoiceDistances(){for(const [id,a] of state.audio){const p=state.players.get(id);if(!p){closePeer(id);continue;}const d=distance(state,p);a.volume=d>VOICE_RADIUS?0:Math.max(0,1-d/VOICE_RADIUS);}if(state.micStream)for(const p of state.players.values())if(distance(state,p)<=VOICE_RADIUS)startVoicePeer(p.id);}
async function toggleMic(){if(state.micStream){state.micStream.getTracks().forEach(t=>t.stop());state.micStream=null;for(const id of [...state.peers.keys()])closePeer(id);micBtn.textContent='🎙️ Activer le micro';voicePill.textContent='🎙️ Micro désactivé';return;}try{state.micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});micBtn.textContent='🔴 Couper le micro';voicePill.textContent='🎙️ Micro actif · proximité';for(const p of state.players.values())if(distance(state,p)<=VOICE_RADIUS)startVoicePeer(p.id);}catch{voicePill.textContent='🎙️ Micro non autorisé';}}
micBtn.addEventListener('click',toggleMic);document.querySelector('#centerBtn').onclick=()=>teleportTo(WORLD.width/2,WORLD.height/2);document.querySelector('#tpBtn').onclick=()=>{const x=Number(document.querySelector('#tpX').value),y=Number(document.querySelector('#tpY').value);if(Number.isFinite(x)&&Number.isFinite(y))teleportTo(x,y);};document.querySelector('#profileBtn').onclick=()=>{document.querySelector('#nameInput').value=state.name;document.querySelector('#profileModal').classList.remove('hidden');};document.querySelector('#closeModal').onclick=()=>document.querySelector('#profileModal').classList.add('hidden');document.querySelector('#saveName').onclick=()=>{const n=document.querySelector('#nameInput').value.trim().replace(/[^\p{L}\p{N}_ -]/gu,'').slice(0,18);if(n){state.name=n;document.querySelector('#profileName').textContent=n;if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({type:'rename',name:n}));}document.querySelector('#profileModal').classList.add('hidden');};document.querySelector('#profileName').textContent=state.name;updateCoords();setInterval(update,50);connect();render();
